"""Workspace module — filesystem backend for team-scoped file operations."""

from akgentic.tool.workspace.actor import (
    WORKSPACE_ACTOR_NAME,
    WORKSPACE_ACTOR_ROLE,
    WorkspaceActor,
    workspace_actor_name,
)
from akgentic.tool.workspace.edit import (
    EditItem,
    EditMatcher,
    FilePatch,
    Hunk,
    MatchResult,
    apply_file_patch,
    detect_line_ending,
    normalise_endings,
    parse_patch,
)
from akgentic.tool.workspace.models import (
    DEFAULT_MAX_OBSERVATIONS_PER_AGENT,
    Observation,
    WorkspaceConfig,
    WorkspaceState,
    content_sha,
)
from akgentic.tool.workspace.readers import (
    TEXT_EXTENSIONS,
    DocumentReader,
    FileTypeReader,
    MediaContent,
)
from akgentic.tool.workspace.tool import (
    ExpandMediaRefs,
    Resource,
    ResourceType,
    WorkspaceDelete,
    WorkspaceEdit,
    WorkspaceGlob,
    WorkspaceGrep,
    WorkspaceList,
    WorkspaceMkdir,
    WorkspaceMultiEdit,
    WorkspacePatch,
    WorkspaceRead,
    WorkspaceTool,
    WorkspaceView,
    WorkspaceWrite,
)
from akgentic.tool.workspace.workspace import (
    FileEntry,
    Filesystem,
    Workspace,
    get_workspace,
    is_staging_name,
)

__all__ = [
    "DEFAULT_MAX_OBSERVATIONS_PER_AGENT",
    "WORKSPACE_ACTOR_NAME",
    "WORKSPACE_ACTOR_ROLE",
    "Observation",
    "WorkspaceActor",
    "WorkspaceConfig",
    "WorkspaceState",
    "content_sha",
    "is_staging_name",
    "workspace_actor_name",
    "DocumentReader",
    "FileTypeReader",
    "MediaContent",
    "TEXT_EXTENSIONS",
    "EditItem",
    "EditMatcher",
    "FilePatch",
    "Hunk",
    "MatchResult",
    "apply_file_patch",
    "detect_line_ending",
    "normalise_endings",
    "parse_patch",
    "FileEntry",
    "Filesystem",
    "Workspace",
    "get_workspace",
    "ExpandMediaRefs",
    "Resource",
    "ResourceType",
    "WorkspaceView",
    "WorkspaceRead",
    "WorkspaceList",
    "WorkspaceGlob",
    "WorkspaceGrep",
    "WorkspaceWrite",
    "WorkspaceDelete",
    "WorkspaceEdit",
    "WorkspaceMultiEdit",
    "WorkspacePatch",
    "WorkspaceMkdir",
    "WorkspaceTool",
]
